on:
  push:
    branches:
    - main
    paths:
      - 'src/**'
      - 'tsconfig.json'
      - 'package.json'
jobs:
  is_build_successful:
    name: Check if project builds successfully
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
